spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager?serverTimezone=GMT%2b8
    username: root
    password: 123456

server:
  port: 9090

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

pagehelper:
  helperDialect: mysql      # 设置数据库方言，支持mysql、oracle等
  reasonable: true          # 启用合理化分页，当页码为0或超过最大页码时，会自动调整
  supportMethodsArguments: true  # 支持通过方法参数传递分页信息
