spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager?serverTimezone=GMT%2b8  # MySQL 数据库连接 URL
    username: root  # 数据库用户名
    password: 123456  # 数据库密码

server:
  port: 9090  # 设置 Spring Boot 服务器端口

mybatis:
  mapper-locations: classpath:mapper/*.xml  # Mapper XML 文件位置
  config-location: classpath:mybatis-config.xml  # MyBatis 配置文件位置
